### ISSUE TITLE
which version of transformers should I use?

### ISSUE THREAD

**Issue by ish505** [xyjigsaw/Text2Graph#1]
when I run your code and load your pkl model file, I got error like this:
`AttributeError: 'T5DenseReluDense' object has no attribute 'relu_act'`

which version of transformers should I use?

**Comment by xyjigsaw** [comment]
Thank you for your attention! We will add requirements.txt later.
python==3.8
transformers==4.25.1
torch==1.10.0

**Comment by ish505** [comment]
> 

3Q for your reply, I update the transformers to 4.25.1, but got this error:
```

File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'T5DenseReluDense' on <module 'transformers.models.t5.modeling_t5'
```

**Comment by ish505** [comment]
> Thank you for your attention! We will add requirements.txt later. python==3.8 transformers==4.25.1 torch==1.10.0

I remove this 4.25.1 version and down to version 4.8.2, then it works~  Thank you~
