### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by rhchosting** [xyjigsaw/Text2Graph#3]
GPU_ID = "0"
os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

use_cuda = torch.cuda.is_available()
if use_cuda:
    print('***************GPU_ID***************: ', GPU_ID)
else:
    raise NotImplementedError
    
    Getting this error 
 line 27, in <module>
    raise NotImplementedError
NotImplementedError

**Comment by xyjigsaw** [comment]
Sorry, you should use at least one GPU to run the model.
